import { icons } from "./icons";

export const tabs: AppTab[] = [
    { name: "index", title: "Roommates", icon: icons.home },
    { name: "chat", title: "Chat", icon: icons.activity },
    { name: "listings", title: "Roommates", icon: icons.wallet },
    { name: "profile", title: "Profile", icon: icons.setting },
];

export const HOME_USER = {
    name: "Nada | Student",
};

export const HOME_BALANCE = {
    amount: 2489.48,
    nextRenewalDate: "2026-09-18T09:00:00.000Z",
};

export const UPCOMING_SUBSCRIPTIONS: UpcomingSubscription[] = [
    {
        id: "spotify",
        icon: icons.spotify,
        name: "Spotify",
        price: 5.99,
        currency: "USD",
        daysLeft: 2,
    },
    {
        id: "notion",
        icon: icons.notion,
        name: "Notion",
        price: 12.0,
        currency: "USD",
        daysLeft: 4,
    },
    {
        id: "figma",
        icon: icons.figma,
        name: "Figma",
        price: 15.0,
        currency: "USD",
        daysLeft: 6,
    },
];

export const LISTINGS: Listing[] = [
    {
        id: "studio-apartment-soho",
        icon: icons.adobe,
        title: "Adobe Creative Cloud",
        image: icons.adobe,
        location: "SoHo, New York",
        beds: 2,
        baths: 2,
        sqft: 1180,
        tags: ["Design District", "Flexible lease", "Utilities included"],
        verified: true,
        landlordName: "Adrian Carter",
        landlordSub: "Verified host",
        name: "Studio apartment in SoHo",
        price: 77.49,
    },
    {
        id: "house-for-rent",
        icon: icons.github,
        title: "GitHub Pro",
        image: icons.github,
        location: "Mission District, San Francisco",
        beds: 1,
        baths: 1,
        sqft: 760,
        tags: ["Walkable", "Co-working nearby", "Pet friendly"],
        verified: true,
        landlordName: "Mia Chen",
        landlordSub: "Top rated host",
        name: "House for rent",
        price: 9.99,
    },
    {
        id: "cozy-apartment-capitol-hill",
        icon: icons.claude,
        title: "Claude Pro",
        image: icons.claude,
        location: "Capitol Hill, Seattle",
        beds: 3,
        baths: 2,
        sqft: 1425,
        tags: ["Rooftop", "Fast Wi-Fi", "Furnished"],
        verified: false,
        landlordName: "Noah Patel",
        landlordSub: "Response within an hour",
        name: "Cozy apartment in Capitol Hill",
        price: 20.0,
    },
    {
        id: "olivias-house-belltown",
        icon: icons.canva,
        title: "Canva Pro",
        image: icons.canva,
        location: "Belltown, Seattle",
        beds: 4,
        baths: 3,
        sqft: 1880,
        tags: ["Family-friendly", "Garage parking", "Garden"],
        verified: true,
        landlordName: "Olivia Reyes",
        landlordSub: "Verified host",
        name: "Olivia's house in Belltown",
        price: 119.99,
    },
];

export const ROOMMATES: Roommate[] = [
    {
        id: "maya-chen",
        icon: icons.claude,
        name: "Maya Chen",
        age: 24,
        school: "NYU",
        location: "Lower East Side",
        bio: "Clean, low-key, and usually studying in the evenings. Looking for someone respectful and easy to live with.",
        budget: "$1,450 / month",
        moveIn: "Sep 1",
        vibe: "Quiet",
        tags: ["Quiet nights", "Study-focused", "No smoking"],
    },
    {
        id: "jordan-reyes",
        icon: icons.canva,
        name: "Jordan Reyes",
        age: 23,
        school: "UCLA",
        location: "Westwood",
        bio: "Social on weekends, organized during the week, and always down for a shared grocery run.",
        budget: "$1,200 / month",
        moveIn: "Aug 20",
        vibe: "Social",
        tags: ["Weekend plans", "Pet friendly", "Shared chores"],
    },
    {
        id: "samir-patel",
        icon: icons.github,
        name: "Samir Patel",
        age: 26,
        school: "Columbia",
        location: "Harlem",
        bio: "Works hybrid, keeps the apartment tidy, and wants a roommate who values routine.",
        budget: "$1,650 / month",
        moveIn: "Oct 1",
        vibe: "Hybrid",
        tags: ["Remote work", "Clean space", "Gym nearby"],
    },
    {
        id: "zoe-baker",
        icon: icons.spotify,
        name: "Zoe Baker",
        age: 22,
        school: "SFSU",
        location: "Mission District",
        bio: "Creative, friendly, and looking for someone who likes a calm home with occasional hangouts.",
        budget: "$1,050 / month",
        moveIn: "Sep 15",
        vibe: "Balanced",
        tags: ["Creative", "Balanced schedule", "No late-night noise"],
    },
];